# Generated by Django 4.2.7 on 2023-12-09 13:42

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Імя/Назва')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Апісанне')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(upload_to=accounts.models.account_avatar_upload_to, verbose_name='Аватар')),
                ('is_published', models.BooleanField(choices=[(0, 'Чарнавік'), (1, 'Апублікавана')], default=0)),
            ],
            options={
                'verbose_name': 'Акаўнт',
                'verbose_name_plural': 'Акаўнты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Катэгорыя',
                'verbose_name_plural': 'Катэгорыі',
            },
        ),
        migrations.CreateModel(
            name='SavedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=accounts.models.account_photos_upload_to, verbose_name='Фота')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_photos', to='accounts.account', verbose_name='Аккаўнт')),
            ],
            options={
                'verbose_name': 'Фота',
                'verbose_name_plural': 'Фота',
            },
        ),
        migrations.CreateModel(
            name='AccountLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category', verbose_name='Катэгорыя'),
        ),
    ]
