# Generated by Django 4.2.7 on 2023-11-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаўнт', 'verbose_name_plural': 'Аккаўнты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Катэгорыя', 'verbose_name_plural': 'Катэгорыі'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фота', 'verbose_name_plural': 'Фота'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Чарнавік'), (1, 'Апаблікавана')], default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category', verbose_name='Катэгорыя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(verbose_name='Апісанне'),
        ),
    ]
