# Generated by Django 4.2.7 on 2023-12-06 14:05

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Загаловак')),
                ('content', models.TextField(verbose_name='Тэкст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час стварэння')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(choices=[(0, 'Чарнавік'), (1, 'Апублікавана')], default=0)),
                ('account', models.ManyToManyField(blank=True, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Артыкул',
                'verbose_name_plural': 'Артыкулы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва катэгорыі')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Катэгорыя',
                'verbose_name_plural': 'Катэгорыі',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=articles.models.article_photos_upload_to, verbose_name='Фота')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_photos', to='articles.article', verbose_name='Артыкул')),
            ],
            options={
                'verbose_name': 'Фота',
                'verbose_name_plural': 'Фота',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlecategory', verbose_name='Катэгорыя'),
        ),
    ]
