version: "3"

services:
  app:
    container_name: skarby
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=skarby
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine
  celery:
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    build:
      context: .
    command: >
      sh -c "celery -A skarby worker -l info && celery -A skarby beat -l info && celery -A skarby flower"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
  flower:
    image: mher/flower:0.9.7
    command: sh -c "celery -A skarby flower"
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
volumes:
  postgres_data:
