# Generated by Django 4.2.7 on 2023-11-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
